mpirun_ops:
  - "-mca pml cm"
  - "-mca mlt psm2"
  - "-bind-to none"
  - "-x PSM2_CUDA=1"
  - "-x PSM2_GPUDIRECT=1"
  - "-x PSM2_CUDA_MEMCACHE_ENABLED=0"  # solves cudaIpcOpenMemHandle() ERROR
  - "-x PSM2_VERBOSE_ENV=2"
  - "-x PSM_CUDA_BOUNCEBUFFERS_MAX=2048"
  - "-x PSM2_GPUDIRECT_RECV_THRESH=30000"
  - "-x PSM2_CUDA_PREFETCH_LIMIT=0"
  - "-x HFI_DEBUG_FILENAME=$HOME/tmp/psm2_debug_%p.log"
  - "-x HFI_DEBUG_TIMEBASE=1"
  - "-x PATH"
  - "-x LIBRARY_PATH"
  - "-x LD_LIBRARY_PATH"
  - "-x CUDA_HOME"
  - "-x CUDA_PATH"
  - "-x CUDA_TOP"
  - "-x CUDA_CACHE_DISABLE=1"
  - "-x NCCL_IB_DISABLE=1"
