nodetype: q_node
nnodes: 1
walltime: 02:30:00
jobname: imagenet
stdout: $JOB_ID.o.log
stderr: $JOB_ID.e.log
others:
  j: "y"

modules:
  cuda: cuda/8.0.61
  cudnn: cudnn/7.0
  nccl: nccl/2.1
  mpi: openmpi/2.1.2

vars: ./modules.sh

nclasses: 16
mean: mean.npy

arch: resnet50
epoch: 10
batchsize: 128
loaderjob: 8
out: results
resume: null
initmodel: /gs/hs0/tgb-crest-deep/17M30275/datasets/initmodels/resnet50.npz
test: null

communicator: hierarchical
loadtype: original
iterator: processes
optimizer: adam
