nnodes: 1
walltime: 24:00:00
jobname: imagenet
stdout: "%A.o.log"
stderr: "%A.e.log"

modules:
  cuda: /usr/local/cuda-9.1
  nccl: /home/users/hiroki11x/env/local/nccl_2.1.15-1+cuda9.1_x86_64
  cudnn: /home/users/hiroki11x/env/local/cuda
  mpi: /home/users/alex/opt/extra/ompi2.1.2

vars: ./modules.sh

nclasses: 1000
mean: mean.npy

train:      /home/share/ILSVRC2012/labels/train.txt
train_root: /home/share/ILSVRC2012/ILSVRC2012_img_train
val:        /home/share/ILSVRC2012/labels/val.txt
val_root:   /home/share/ILSVRC2012/ILSVRC2012_img_val
arch: resnet50
epoch: 100
batchsize: 64
loaderjob: 8
out: /home/users/hiroki11x/out
resume: null
initmodel: null
test: null

communicator: hierarchical
loadtype: development
iterator: thread
optimizer: momentum_sgd
