nnodes: 1
walltime: 00:30:00
jobname: imagenet
stdout: "%A.o.log"
stderr: "%A.e.log"

modules:
  cuda: cuda/9.1
  nccl: local/nccl/2.1.15
  cudnn: local/cudnn/7.1
  mpi: local/openmpi/2.1.3/cuda-9.1

vars: ./modules.sh

nclasses: 8
mean: mean.npy

train:      /home/share/ILSVRC2012/labels/train008.txt
train_root: /home/share/ILSVRC2012/ILSVRC2012_img_train
val:        /home/share/ILSVRC2012/labels/val008.txt
val_root:   /home/share/ILSVRC2012/ILSVRC2012_img_val
arch: resnet50
epoch: 2
batchsize: 64
loaderjob: 8
out: /home/users/Yohei/results/dlframeworks
resume: null
initmodel: null
test: null

communicator: hierarchical
loadtype: development
iterator: thread
optimizer: adam
